import $ from './core';
import './modules/display';
import './modules/classes';
import './modules/handlers';
import './modules/attributes';
import './modules/actions';
import './modules/effects';
import './components/ui';
import './services/request';
export default $;
